name: build-and-test

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '**.adoc'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '**.adoc'
      - '**.txt'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.0', '3.1', '3.2' ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false

    - name: Build and test with Rake
      run: |
        bundle install
        rake test

# ----- Release -----
  release:
    name: Release gem
    needs: [ build ]
    runs-on: windows-latest
    if: contains(github.ref, 'refs/tags/v') && !contains(github.ref, 'pre')
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        submodules: true

    - uses: cadwallion/publish-rubygems-action@master
      env:
        RUBYGEMS_API_KEY: ${{secrets.TEBAKO_CI_RUBYGEMS_API_KEY}}
